import { beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { checkProject, compileProject } from "./compile";
import { renderApplication } from "./generate";
import { BAD_PROJECT_FILES } from "./fixtures/bad-project";
import { GOOD_PROJECT_FILES } from "./fixtures/good-project";
import { writeFixtureProject } from "./fixtures/helpers";
import { FIXTURE_TSCONFIG, RUNTIME_SOURCE } from "./fixtures/runtime-source";
import { scanGeneratedArtifacts } from "./type-safety";
import type { ApplicationGraph, CompileResult } from "./types";

let rootDir: string;
let outDir: string;
let result: CompileResult;
let applicationCode: string;

beforeAll(async () => {
  rootDir = await mkdtemp(join(tmpdir(), "supacloud-compiler-gen-"));
  await writeFixtureProject(rootDir, GOOD_PROJECT_FILES);
  outDir = join(rootDir, "generated");
  result = await compileProject({ rootDir, outDir });
  applicationCode = await readFile(join(outDir, "application.ts"), "utf8");
}, 30_000);

describe("compileProject：总体结果", () => {
  test("无诊断，写出 application.ts 与 app.manifest.json", () => {
    expect(result.diagnostics).toEqual([]);
    expect(result.written).toEqual([
      join(outDir, "application.ts"),
      join(outDir, "app.manifest.json"),
    ]);
  });

  test("严格生成产物不包含 any", () => {
    expect(scanGeneratedArtifacts({ "application.ts": applicationCode })).toEqual([]);
  });

  test("app.manifest.json 是 graph 的 JSON 序列化", async () => {
    const manifest = JSON.parse(
      await readFile(join(outDir, "app.manifest.json"), "utf8"),
    );
    expect(manifest.version).toBe(1);
    expect(manifest.externalTokens).toEqual(["DB_CLIENT", "REQUEST_CONTEXT"]);
    expect(manifest.modules.map((m: { name: string }) => m.name).sort()).toEqual([
      "audit",
      "case",
      "health",
    ]);
  });
});

describe("generate：application.ts 关键内容", () => {
  test("头注释与本地接口定义（不 import 外部包）", () => {
    expect(applicationCode).toStartWith(
      "// GENERATED BY @supacloud/compiler — do not edit",
    );
    expect(applicationCode).toContain("export interface CompiledModule {");
    expect(applicationCode).toContain("export interface CompiledController {");
    expect(applicationCode).toContain("export interface CompiledRoute {");
    expect(applicationCode).toContain("export interface CompiledCommand {");
    expect(applicationCode).not.toContain("@supacloud/app");
    expect(applicationCode).not.toContain("@supacloud/elysia");
  });

  test("业务类与 schema 以相对路径 import", () => {
    expect(applicationCode).toContain(
      'import { AuditService } from "../src/features/audit/audit.service";',
    );
    expect(applicationCode).toContain(
      'import { createLogger } from "../src/features/audit/logger";',
    );
    expect(applicationCode).toContain(
      'import { DrizzleCaseRepository } from "../src/features/case/case.repository";',
    );
    expect(applicationCode).toContain(
      'import { AcceptParams, AcceptResult, CreateCaseBody } from "../src/features/case/contracts";',
    );
  });

  test("模块按 imports 拓扑序出现在 createCompiledModules", () => {
    const auditIndex = applicationCode.indexOf('name: "audit"');
    const caseIndex = applicationCode.indexOf('name: "case"');
    const healthIndex = applicationCode.indexOf('name: "health"');
    expect(auditIndex).toBeGreaterThan(-1);
    expect(auditIndex).toBeLessThan(caseIndex);
    expect(caseIndex).toBeLessThan(healthIndex);
  });

  test("application 工厂：value/factory/class/existing 实例化与依赖解析", () => {
    expect(applicationCode).toContain('const auditConfig = { level: "info" };');
    expect(applicationCode).toContain("const logger = createLogger(auditConfig);");
    expect(applicationCode).toContain(
      "const auditService = new AuditService(auditConfig, logger);",
    );
    expect(applicationCode).toContain(
      "const caseRepository = new DrizzleCaseRepository(deps.dbClient);",
    );
    expect(applicationCode).toContain(
      "const caseService = new CaseService(caseRepository, imported.audit.auditService);",
    );
    expect(applicationCode).toContain(
      "const acceptCaseCommand = new AcceptCaseCommand(caseService);",
    );
  });

  test("property-level inject() uses a generated static token identity context", () => {
    const rendered = renderApplication({
      modules: [{
        name: "functional",
        className: "FunctionalModule",
        file: "src/functional.module.ts",
        line: 1,
        imports: [],
        providers: [{
          token: "CONFIG",
          tokenKind: "injection-token",
          kind: "value",
          useValueExpr: '{ mode: "strict" }',
          scope: "application",
          deps: [],
          exported: false,
          file: "src/functional.module.ts",
          line: 1,
        }, {
          token: "FunctionalService",
          tokenKind: "class",
          kind: "class",
          useClass: "FunctionalService",
          scope: "application",
          deps: ["CONFIG"],
          functionalInjects: [{
            token: "CONFIG",
            expression: "CONFIG",
            importPath: "src/functional.module",
          }],
          exported: false,
          file: "src/functional.module.ts",
          line: 1,
          importPath: "src/functional.service",
        }],
        controllers: [],
        commands: [],
        queries: [],
        exports: [],
      }],
      externalTokens: [],
    }, {
      rootDir: "/app",
      outDir: "/app/generated",
    });

    expect(rendered.applicationCode).toContain('import { runInInjectionContext } from "@supacloud/app";');
    expect(rendered.applicationCode).toContain("if (token === CONFIG) return config as T;");
    expect(rendered.applicationCode).toContain("runInInjectionContext({");
    expect(rendered.applicationCode).not.toContain("new StaticInjector");
  });

  test("request 工厂：REQUEST_CONTEXT 传 ctx，其余从 services 解析", () => {
    expect(applicationCode).toContain("createCaseRequestScope");
    expect(applicationCode).toContain(
      "const caseController = new CaseController(services.caseRepository, imported.audit.auditService, ctx);",
    );
  });

  test("controller 描述静态给出，schema 直接引用导入对象", () => {
    expect(applicationCode).toContain('serviceKey: "caseController"');
    expect(applicationCode).toContain('path: "/cases"');
    expect(applicationCode).toContain(
      'handler: "accept", body: CreateCaseBody, params: AcceptParams, response: AcceptResult, command: "AcceptCaseCommand", invoker: async (ctrl: unknown',
    );
  });

  test("生成静态 aspect import 与固定调用列表", () => {
    const rendered = renderApplication({
      modules: [{
        name: "aspect",
        className: "AspectModule",
        file: "src/aspect.module.ts",
        line: 1,
        imports: [],
        providers: [],
        controllers: [{
          className: "AspectController",
          path: "/aspect",
          scope: "application",
          deps: [],
          routes: [{
            method: "GET",
            path: "/",
            handler: "get",
            aspects: [{
              name: "routeAspect",
              expression: "routeAspect",
              importPath: "src/aspects",
            }],
          }],
          file: "src/aspect.controller.ts",
          importPath: "src/aspect.controller",
        }],
        commands: [{
          className: "AspectCommand",
          name: "aspect.run",
          permission: "aspect.run",
          transaction: "none",
          idempotency: "none",
          aspects: [{
            name: "commandAspect",
            expression: "commandAspect",
            importPath: "src/aspects",
          }],
        }],
        jobs: [{
          className: "RebuildJob",
          name: "aspect.rebuild",
          serviceKey: "rebuildJob",
          scope: "job",
        }],
        queries: [],
        aspects: [{
          name: "moduleAspect",
          expression: "moduleAspect",
          importPath: "src/aspects",
        }],
        exports: [],
      }],
      externalTokens: [],
    }, { rootDir: "/app", outDir: "/app/generated" });

    expect(rendered.applicationCode).toContain(
      'import { commandAspect, moduleAspect, routeAspect } from "../src/aspects";',
    );
    expect(rendered.applicationCode).toContain("aspects: [routeAspect]");
    expect(rendered.applicationCode).toContain("aspects: [commandAspect]");
    expect(rendered.applicationCode).toContain("aspects: [moduleAspect]");
    expect(rendered.applicationCode).toContain(
      'jobs: [{ className: "RebuildJob", name: "aspect.rebuild", serviceKey: "rebuildJob", scope: "job", }]',
    );
    expect(rendered.applicationCode).not.toContain("Reflect.get");
    expect(rendered.applicationCode).not.toContain("Proxy");
  });

  test("scope factory 在 provider 构造失败时回滚已创建实例", async () => {
    const fixtureRoot = await mkdtemp(join(tmpdir(), "supacloud-job-rollback-"));
    await writeFixtureProject(fixtureRoot, {
      "tsconfig.json": FIXTURE_TSCONFIG,
      "src/runtime.ts": RUNTIME_SOURCE,
      "src/jobs.module.ts": `
        import { Injectable, Job, Module } from "./runtime";

        @Injectable({ scope: "job" })
        export class CreatedBeforeFailure {
          onDestroy() {
            (globalThis as Record<string, unknown>).__supacloudRollbackCount =
              ((globalThis as Record<string, unknown>).__supacloudRollbackCount as number ?? 0) + 1;
          }
        }

        @Injectable({ scope: "job" })
        export class FailingProvider {
          constructor() { throw new Error("factory failure"); }
        }

        @Job({ name: "jobs.rollback" })
        export class RollbackJob {
          constructor(_created: CreatedBeforeFailure, _failing: FailingProvider) {}
          run(input: string) { return input; }
        }

        @Module({
          name: "jobs",
          providers: [CreatedBeforeFailure, FailingProvider],
          jobs: [RollbackJob],
        })
        export class JobsModule {}
      `,
    });
    const output = join(fixtureRoot, "generated");
    const result = await compileProject({ rootDir: fixtureRoot, outDir: output });
    expect(result.diagnostics).toEqual([]);
    const generated = await import(pathToFileURL(join(output, "application.ts")).href);
    const compiled = generated.createCompiledModules()[0];
    (globalThis as Record<string, unknown>).__supacloudRollbackCount = 0;
    await expect(compiled.createJobScope({}, {})).rejects.toThrow("factory failure");
    expect((globalThis as Record<string, unknown>).__supacloudRollbackCount).toBe(1);
    delete (globalThis as Record<string, unknown>).__supacloudRollbackCount;
  });
});

describe("generate：application.ts 可被 bun 直接执行", () => {
  type RuntimeServices = {
    auditConfig: { level: string };
    logger: { level: string };
    auditService: { config: unknown; logger: unknown };
    caseRepository: { db: unknown };
    caseService: { repository: unknown; audit: unknown };
    acceptCaseCommand: { caseService: unknown };
    healthService: { status: () => string };
    caseController: { ctx: unknown; repository: unknown; audit: unknown };
  };
  type RuntimeModule = {
    name: string;
    commands: Array<{ className: string; name: string; permission: string }>;
    controllers: Array<{
      path: string;
      serviceKey: string;
      scope: string;
      routes: Array<{ body?: unknown; params?: unknown; response?: unknown }>;
    }>;
    createServices: (deps: Record<string, unknown>, imported: Record<string, Partial<RuntimeServices>>) => RuntimeServices;
    createRequestScope?: (
      services: RuntimeServices,
      ctx: unknown,
      imported?: Record<string, Partial<RuntimeServices>>,
    ) => Promise<RuntimeServices>;
    destroyRequestScope?: (scope: RuntimeServices) => Promise<void>;
  };
  let compiled: {
    createCompiledModules: () => RuntimeModule[];
  };

  beforeAll(async () => {
    const url = pathToFileURL(join(outDir, "application.ts")).href;
    compiled = await import(url);
  });

  test("createCompiledModules 返回拓扑序模块描述", () => {
    const modules = compiled.createCompiledModules();
    expect(modules.map((m: { name: string }) => m.name)).toEqual([
      "audit",
      "case",
      "health",
    ]);
    expect(modules[0].controllers).toEqual([]);
    expect(modules[1].commands[0]).toMatchObject({
      className: "AcceptCaseCommand",
      name: "case.accept",
      permission: "case.accept",
    });
    expect(typeof modules[1].createRequestScope).toBe("function");
    expect(typeof modules[1].destroyRequestScope).toBe("function");
    expect(modules[2].createRequestScope).toBeUndefined();
  });

  test("services 实例化与跨模块依赖注入", () => {
    const modules = compiled.createCompiledModules();
    const deps = { dbClient: { kind: "fake-db" } };

    const auditServices = modules[0].createServices(deps, {});
    expect(auditServices.auditConfig).toEqual({ level: "info" });
    expect(auditServices.logger).toEqual({ level: "info" });
    expect(auditServices.auditService.config).toEqual({ level: "info" });
    expect(auditServices.auditService.logger).toBe(auditServices.logger);

    const caseServices = modules[1].createServices(deps, { audit: auditServices });
    expect(caseServices.caseRepository.db).toBe(deps.dbClient);
    expect(caseServices.caseService.repository).toBe(caseServices.caseRepository);
    expect(caseServices.caseService.audit).toBe(auditServices.auditService);
    expect(caseServices.acceptCaseCommand.caseService).toBe(caseServices.caseService);

    const healthServices = modules[2].createServices(deps, {});
    expect(healthServices.healthService.status()).toBe("ok");
  });

  test("request scope：ctx 注入且两次调用相互隔离", async () => {
    const modules = compiled.createCompiledModules();
    const deps = { dbClient: {} };
    const caseModule = modules[1];
    const services = caseModule.createServices(deps, {
      audit: modules[0].createServices(deps, {}),
    });

    const ctx1 = { requestId: "r1" };
    const ctx2 = { requestId: "r2" };
    const imported = { audit: modules[0].createServices(deps, {}) };
    const createRequestScope = caseModule.createRequestScope;
    if (!createRequestScope) throw new Error("request scope factory is missing");
    const scope1 = await createRequestScope(services, ctx1, imported);
    const scope2 = await createRequestScope(services, ctx2, imported);

    expect(scope1.caseController.ctx).toBe(ctx1);
    expect(scope1.caseController.repository).toBe(services.caseRepository);
    expect(scope1.caseController.audit).toBe(imported.audit.auditService);
    expect(scope2.caseController.ctx).toBe(ctx2);
    expect(scope2.caseController).not.toBe(scope1.caseController);
  });

  test("controller 路由 schema 引用与 contracts 模块导出的对象同一", async () => {
    const contracts = await import(
      pathToFileURL(join(rootDir, "src/features/case/contracts.ts")).href
    );
    const modules = compiled.createCompiledModules();
    const controller = modules[1].controllers[0];
    expect(controller.path).toBe("/cases");
    expect(controller.serviceKey).toBe("caseController");
    expect(controller.scope).toBe("request");
    expect(controller.routes).toHaveLength(1);
    expect(controller.routes[0].body).toBe(contracts.CreateCaseBody);
    expect(controller.routes[0].params).toBe(contracts.AcceptParams);
    expect(controller.routes[0].response).toBe(contracts.AcceptResult);
  });

  test("checkProject reports matching artifacts and detects drift", async () => {
    // 1. Freshly generated artifacts match.
    const check1 = await checkProject({ rootDir, outDir });
    expect(check1.upToDate).toBe(true);
    expect(check1.mismatches).toHaveLength(0);

    // 2. Tampering with a file must be detected.
    const manifestPath = join(outDir, "app.manifest.json");
    const originalContent = await readFile(manifestPath, "utf8");
    await writeFile(manifestPath, '{"tampered": true}\n', "utf8");

    try {
      const check2 = await checkProject({ rootDir, outDir });
      expect(check2.upToDate).toBe(false);
      expect(check2.mismatches.some((m) => m.includes("app.manifest.json"))).toBe(true);
    } finally {
      await writeFile(manifestPath, originalContent, "utf8");
    }
  });

  test("writeOnError=false 保留既有生成物，不写入错误版本", async () => {
    const badRoot = await mkdtemp(join(tmpdir(), "supacloud-compiler-error-"));
    const badOut = join(badRoot, "generated");
    await writeFixtureProject(badRoot, GOOD_PROJECT_FILES);
    const first = await compileProject({ rootDir: badRoot, outDir: badOut });
    expect(first.diagnostics).toEqual([]);
    const original = await readFile(join(badOut, "application.ts"), "utf8");

    await writeFixtureProject(badRoot, BAD_PROJECT_FILES);
    const failed = await compileProject({ rootDir: badRoot, outDir: badOut, writeOnError: false });
    expect(failed.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(true);
    expect(failed.written).toEqual([]);
    expect(await readFile(join(badOut, "application.ts"), "utf8")).toBe(original);
  });
});

describe("generate：client.ts 与 permissions.ts 端到端代码生成", () => {
  test("compileProject 带 generateClient 和 generatePermissions 生成 client.ts 与 permissions.ts", async () => {
    const fullOut = join(rootDir, "generated-full");
    const fullResult = await compileProject({
      rootDir,
      outDir: fullOut,
      generateClient: true,
      generatePermissions: true,
    });
    expect(fullResult.diagnostics).toEqual([]);
    expect(fullResult.written).toContain(join(fullOut, "client.ts"));
    expect(fullResult.written).toContain(join(fullOut, "permissions.ts"));

    const clientCode = await readFile(join(fullOut, "client.ts"), "utf8");
    expect(clientCode).toContain("export function createApiClient");
    expect(clientCode).toContain("export const API_ROUTES =");
    expect(clientCode).toContain("case: {");
    expect(clientCode).toContain("accept: makeRoute<");

    const permissionsCode = await readFile(join(fullOut, "permissions.ts"), "utf8");
    expect(permissionsCode).toContain("export const AppPermissions =");
    expect(permissionsCode).toContain('CaseAccept: "case.accept"');
    expect(permissionsCode).toContain("export const RoutePermissions:");
    expect(permissionsCode).toContain("export function hasPermission");

    const clientModule = await import(pathToFileURL(join(fullOut, "client.ts")).href);
    expect(Array.isArray(clientModule.API_ROUTES)).toBe(true);
    expect(clientModule.API_ROUTES[0]).toMatchObject({
      method: "POST",
      path: "/cases/:caseId/accept",
      controller: "CaseController",
      handler: "accept",
    });

    const permissionsModule = await import(pathToFileURL(join(fullOut, "permissions.ts")).href);
    expect(permissionsModule.AppPermissions.CaseAccept).toBe("case.accept");
    expect(permissionsModule.hasPermission(["case.accept"], "case.accept")).toBe(true);
    expect(permissionsModule.hasPermission(["*"], "case.accept")).toBe(true);
    expect(permissionsModule.hasPermission(["other"], "case.accept")).toBe(false);
  });

  test("renderApplication outputs guards and resolvers in controller routes", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "admin",
            className: "AdminModule",
            file: "src/admin.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "AdminController",
                path: "/admin",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/dashboard",
                    handler: "dashboard",
                    guards: ["authGuard", "roleGuard"],
                    resolvers: { stats: "statsResolver" },
                  },
                ],
                file: "src/admin.controller.ts",
                importPath: "./admin.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain('guards: ["authGuard","roleGuard"]');
    expect(rendered.applicationCode).toContain('resolvers: {"stats":"statsResolver"}');
    expect(rendered.clientCode).toContain('"guards": [\n      "authGuard",\n      "roleGuard"\n    ]');
  });

  test("compileProject auto-discovers standalone controllers and commands into root module", async () => {
    const standaloneDir = await mkdtemp(join(tmpdir(), "supacloud-standalone-"));
    await writeFixtureProject(standaloneDir, {
      "tsconfig.json": GOOD_PROJECT_FILES["tsconfig.json"],
      "src/standalone.controller.ts": `
        import { Controller, Get, UseGuards } from "@supacloud/app";

        @UseGuards("authGuard")
        @Controller({ path: "/standalone", standalone: true })
        export class StandaloneController {
          @Get("/ping")
          ping() { return "pong"; }
        }
      `,
      "src/standalone.command.ts": `
        import { Command } from "@supacloud/app";

        @Command({ name: "standalone.run", permission: "standalone.run", standalone: true })
        export class StandaloneCommand {}
      `,
    });

    const out = join(standaloneDir, "gen");
    const res = await compileProject({ rootDir: standaloneDir, outDir: out, generateClient: true });
    expect(res.diagnostics).toEqual([]);
    const rootMod = res.graph.modules.find((m) => m.name === "root");
    expect(rootMod).toBeDefined();
    expect(rootMod?.controllers.map((c) => c.className)).toContain("StandaloneController");
    expect(rootMod?.commands.map((c) => c.className)).toContain("StandaloneCommand");

    const appCode = await readFile(join(out, "application.ts"), "utf8");
    expect(appCode).toContain('path: "/standalone"');
    expect(appCode).toContain('guards: ["authGuard"]');
  });

  test("renderApplication generates initializeApplication and redirectTo/pathMatch", async () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "routes",
            className: "RoutesModule",
            file: "src/routes.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "RedirectController",
                path: "/redirect",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/",
                    handler: "index",
                    redirectTo: "/redirect/target",
                    pathMatch: "full",
                  },
                ],
                file: "src/redirect.controller.ts",
                importPath: "./redirect.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain("export async function initializeApplication(");
    expect(rendered.applicationCode).toContain('redirectTo: "/redirect/target"');
    expect(rendered.applicationCode).toContain('pathMatch: "full"');
    expect(rendered.clientCode).toContain("export type HttpInterceptorFn");
    expect(rendered.clientCode).toContain("interceptors?: HttpInterceptorFn[];");
  });

  test("renderApplication generates destroyApplication and executes teardown in reverse order", async () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "items",
            className: "ItemsModule",
            file: "src/items.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "ItemsController",
                path: "/items",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/:id",
                    handler: "getItem",
                    canMatch: ["matchGuard"],
                    paramTransforms: { id: "number" },
                    queryTransforms: { page: "number" },
                    queryDefaults: { page: 1 },
                  },
                ],
                file: "src/items.controller.ts",
                importPath: "./items.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain("export async function destroyApplication(");
    expect(rendered.applicationCode).toContain('canMatch: ["matchGuard"]');
    expect(rendered.applicationCode).toContain('paramTransforms: {"id":"number"}');
    expect(rendered.applicationCode).toContain('queryTransforms: {"page":"number"}');
    expect(rendered.applicationCode).toContain('queryDefaults: {"page":1}');
    expect(rendered.clientCode).toContain('"canMatch": [');
    expect(rendered.clientCode).toContain('"matchGuard"');

    // Evaluate destroyApplication execution using compiled artifacts from beforeAll
    const teardownOrder: string[] = [];
    const mockServices = {
      firstService: {
        onDestroy() {
          teardownOrder.push("firstService");
        },
      },
      secondService: {
        onDestroy() {
          teardownOrder.push("secondService");
        },
      },
      destroyRef: {
        _teardowns: [
          () => {
            teardownOrder.push("destroyRef-first");
          },
          () => {
            teardownOrder.push("destroyRef-second");
          },
        ],
      },
    };

    const compiledMod = await import(pathToFileURL(join(outDir, "application.ts")).href);
    await compiledMod.destroyApplication(mockServices);

    // destroyRef teardowns in reverse, then services in reverse
    expect(teardownOrder).toEqual([
      "destroyRef-second",
      "destroyRef-first",
      "secondService",
      "firstService",
    ]);
  });

  test("renderApplication and renderClient generate route title and static data metadata", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "meta",
            className: "MetaModule",
            file: "src/meta.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "MetaController",
                path: "/meta",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/info",
                    handler: "getInfo",
                    title: "System Information",
                    data: { tier: "enterprise", public: false },
                  },
                ],
                file: "src/meta.controller.ts",
                importPath: "./meta.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain('title: "System Information"');
    expect(rendered.applicationCode).toContain('data: {"tier":"enterprise","public":false}');
    expect(rendered.clientCode).toContain('"title": "System Information"');
    expect(rendered.clientCode).toContain('"tier": "enterprise"');
  });

  test("renderApplication and renderClient emit canDeactivate guards and tree-shakable token factory", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "guardModule",
            className: "GuardModule",
            file: "src/guard.module.ts",
            line: 1,
            imports: [],
            providers: [
              {
                token: "API_URL",
                tokenKind: "injection-token",
                kind: "factory",
                scope: "application",
                deps: [],
                importPath: "./tokens",
                exported: true,
                file: "src/tokens.ts",
                line: 1,
              },
            ],
            controllers: [
              {
                className: "GuardController",
                path: "/guarded",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "POST",
                    path: "/step",
                    handler: "submitStep",
                    canDeactivate: ["UnsavedGuard"],
                  },
                ],
                file: "src/guard.controller.ts",
                importPath: "./guard.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain('canDeactivate: ["UnsavedGuard"]');
    expect(rendered.applicationCode).toContain("const apiUrl = resolveFactoryValue(API_URL);");
    expect(rendered.clientCode).toContain('"canDeactivate": [\n      "UnsavedGuard"\n    ]');
  });

  test("renderClient generates typed route parameter signatures and buildRouteUrl helper", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "RouteModule",
            className: "RouteModule",
            file: "src/route.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "UsersController",
                path: "/orgs/:orgId/users",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/:userId",
                    handler: "getUser",
                    pathParams: ["orgId", "userId"],
                  },
                  {
                    method: "GET",
                    path: "/",
                    handler: "listUsers",
                    pathParams: ["orgId"],
                  },
                ],
                file: "src/users.controller.ts",
                importPath: "./users.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.clientCode).toContain("params: { orgId: string | number; userId: string | number }");
    expect(rendered.clientCode).toContain("params: { orgId: string | number }");
    expect(rendered.clientCode).toContain("export function buildRouteUrl(");
    expect(rendered.clientCode).toContain("export type AppRoutePath = typeof API_ROUTES[number]['path'];");
    expect(rendered.clientCode).toContain("buildRouteUrl,");
    expect(rendered.clientCode).toContain("routes: API_ROUTES,");
  });

  test("renderClient does not assert unvalidated network responses to application types", () => {
    const rendered = renderApplication(
      {
        modules: [{
          name: "api",
          className: "ApiModule",
          file: "src/api.module.ts",
          line: 1,
          imports: [],
          providers: [],
          controllers: [{
            className: "ApiController",
            path: "/api",
            scope: "request",
            deps: [],
            routes: [{ method: "GET", path: "/value", handler: "value" }],
            file: "src/api.controller.ts",
            importPath: "./api.controller",
          }],
          commands: [],
          queries: [],
          exports: [],
        }],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.clientCode).toContain("export type ResponseDecoder<T> = (value: unknown) => T;");
    expect(rendered.clientCode).toContain("): Promise<unknown>;");
    expect(rendered.clientCode).toContain("value = await response.json();");
    expect(rendered.clientCode).toContain("return decode ? decode(value) : value;");
    expect(rendered.clientCode).not.toContain("response.json() as Promise<T>");
    expect(rendered.clientCode).not.toContain("response.text() as Promise<T>");
  });

  test("treeShakeUnusedProviders prunes unreferenced root providers from compiled modules", () => {
    const graph: ApplicationGraph = {
      modules: [
        {
          name: "TestModule",
          className: "TestModule",
          file: "src/test.module.ts",
          line: 1,
          imports: [],
          providers: [
            {
              token: "UsedService",
              tokenKind: "class",
              kind: "class",
              scope: "application",
              providedIn: "root",
              deps: [],
              exported: false,
              file: "src/used.service.ts",
              line: 5,
            },
            {
              token: "DeadService",
              tokenKind: "class",
              kind: "class",
              scope: "application",
              providedIn: "root",
              deps: [],
              exported: false,
              file: "src/dead.service.ts",
              line: 10,
            },
          ],
          controllers: [
            {
              className: "TestController",
              path: "/test",
              scope: "request",
              deps: ["UsedService"],
              routes: [],
              file: "src/test.controller.ts",
              importPath: "./test.controller",
            },
          ],
          commands: [],
          queries: [],
          exports: [],
        },
      ],
      externalTokens: [],
    };

    const withoutTreeShaking = renderApplication(graph, {
      rootDir: "/app",
      outDir: "/app/gen",
      treeShakeUnusedProviders: false,
    });
    expect(withoutTreeShaking.applicationCode).toContain("DeadService");

    const withTreeShaking = renderApplication(graph, {
      rootDir: "/app",
      outDir: "/app/gen",
      treeShakeUnusedProviders: true,
    });
    expect(withTreeShaking.applicationCode).toContain("UsedService");
    expect(withTreeShaking.applicationCode).not.toContain("DeadService");
  });

  test("renderApplication generates typed route invoker with parameter and query coercion", () => {
    const graph: ApplicationGraph = {
      modules: [
        {
          name: "users",
          className: "UsersModule",
          file: "src/users.module.ts",
          line: 1,
          imports: [],
          providers: [],
          controllers: [
            {
              className: "UsersController",
              path: "/users",
              scope: "request",
              deps: [],
              routes: [
                {
                  method: "GET",
                  path: "/:id",
                  handler: "getUser",
                  pathParams: ["id"],
                  paramBindings: ["id"],
                  paramTransforms: { id: "number" },
                  queryBindings: ["limit"],
                  queryTransforms: { limit: "number" },
                  queryDefaults: { limit: 20 },
                  handlerParams: [
                    { name: "id", kind: "param", bindingName: "id", transform: "number" },
                    { name: "limit", kind: "query", bindingName: "limit", transform: "number", default: 20 },
                    { name: "body", kind: "body" },
                  ],
                },
              ],
              file: "src/users.controller.ts",
              importPath: "./users.controller",
            },
          ],
          commands: [],
          queries: [],
          exports: [],
        },
      ],
      externalTokens: [],
    };

    const rendered = renderApplication(graph, {
      rootDir: "/app",
      outDir: "/app/gen",
    });
    expect(rendered.applicationCode).toContain("invoker: async (ctrl: unknown, req:");
    expect(rendered.applicationCode).toContain('const handler = ctrl["getUser"];');
    expect(rendered.applicationCode).toContain("Reflect.apply(handler, ctrl");
    expect(rendered.applicationCode).toContain('Number(req.params?.["id"])');
    expect(rendered.applicationCode).toContain('Number(req.query?.["limit"])');
    expect(rendered.applicationCode).toContain(": 20");
  });

  test("renderApplication emits static request-scope destruction plans", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "scoped",
            className: "ScopedModule",
            file: "src/scoped.module.ts",
            line: 1,
            imports: [],
            providers: [
              {
                token: "REQUEST_RESOURCE",
                tokenKind: "injection-token",
                kind: "class",
                useClass: "RequestResource",
                scope: "request",
                deps: [],
                hasOnDestroy: true,
                exported: false,
                file: "src/request-resource.ts",
                line: 1,
                importPath: "./request-resource",
              },
            ],
            controllers: [
              {
                className: "ScopedController",
                path: "/scoped",
                scope: "request",
                deps: [],
                hasOnDestroy: true,
                routes: [],
                file: "src/scoped.controller.ts",
                importPath: "./scoped.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/generated" },
    );

    expect(rendered.applicationCode).toContain(
      "async function destroyScopedRequestScope(scope: Record<string, unknown>): Promise<void>",
    );
    expect(rendered.applicationCode).toContain(
      'await destroyScopeInstances(scope, [{"key":"requestResource"},{"key":"scopedController"}]);',
    );
  });
});
