import { createHash } from "node:crypto";
import { access, mkdir, rename, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ApplicationGraph,
  AspectRefNode,
  ControllerNode,
  FunctionalInjectNode,
  ModuleNode,
  ProviderNode,
  Scope,
} from "./types";
import {
  camelName,
  isJobContextToken,
  isRequestContextToken,
  joinRoutePaths,
  relativeImportPath,
} from "./util";

const HEADER = "// GENERATED BY @supacloud/compiler — do not edit";

const INTERFACES = `export interface CompiledRoute {
  method: string;
  path: string;
  handler: string;
  body?: unknown;
  params?: unknown;
  query?: unknown;
  response?: unknown;
  command?: string;
  guards?: string[];
  canMatch?: string[];
  canDeactivate?: string[];
  resolvers?: Record<string, string>;
  redirectTo?: string;
  pathMatch?: "full" | "prefix";
  paramTransforms?: Record<string, "number" | "boolean" | "string">;
  paramDefaults?: Record<string, unknown>;
  queryTransforms?: Record<string, "number" | "boolean" | "string">;
  queryDefaults?: Record<string, unknown>;
  title?: string;
  data?: Record<string, unknown>;
  aspects?: CompiledAspect[];
  invoker?: (
    controller: unknown,
    request: {
      params?: Record<string, unknown>;
      query?: Record<string, unknown>;
      body?: unknown;
      headers?: Record<string, unknown>;
      context?: unknown;
    },
  ) => Promise<unknown> | unknown;
}

export interface CompiledCommand {
  className: string;
  name: string;
  permission: string;
  transaction: "required" | "none";
  audit?: string;
  idempotency: "required" | "none";
  standalone?: boolean;
  aspects?: CompiledAspect[];
}

export interface CompiledJob {
  className: string;
  name: string;
  serviceKey: string;
  scope: "application" | "request" | "job";
  aspects?: CompiledAspect[];
}

export interface CompiledAspectContext {
  kind: "route" | "command" | "job";
  name: string;
  input: unknown;
  request?: Request;
  requestContext?: unknown;
  scope?: Record<string, unknown>;
  services?: Record<string, unknown>;
  metadata?: unknown;
}

export type CompiledAspect = (
  context: CompiledAspectContext,
  next: () => unknown | Promise<unknown>,
) => unknown | Promise<unknown>;

export interface CompiledController {
  path: string;
  serviceKey: string;
  scope: string;
  routes: CompiledRoute[];
}

export interface CompiledModule {
  name: string;
  createServices(
    deps: Record<string, unknown>,
    imported: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  createRequestScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Promise<Record<string, unknown>>;
  destroyRequestScope?(scope: Record<string, unknown>): Promise<void>;
  createJobScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Promise<Record<string, unknown>>;
  destroyJobScope?(scope: Record<string, unknown>): Promise<void>;
  controllers: CompiledController[];
  commands: CompiledCommand[];
  jobs: CompiledJob[];
  aspects?: CompiledAspect[];
}`;

const TYPE_GUARDS = `function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isFunction(value: unknown): value is (...args: unknown[]) => unknown {
  return typeof value === "function";
}

function resolveFactoryValue(value: unknown): unknown {
  if (!isRecord(value) || !isFunction(value.factory)) return undefined;
  return value.factory();
}

const scopeDestructions = new WeakMap<object, Promise<void>>();

function destroyScopeInstances(
  scope: Record<string, unknown>,
  plan: readonly { key: string; index?: number }[],
): Promise<void> {
  const pending = scopeDestructions.get(scope);
  if (pending) return pending;
  const destruction = Promise.resolve().then(async () => {
    const errors: unknown[] = [];
    const seen = new Set<unknown>();
    for (const entry of [...plan].reverse()) {
      const value = scope[entry.key];
      const instance = entry.index === undefined ? value
        : Array.isArray(value) ? value[entry.index] : undefined;
      if (seen.has(instance)) continue;
      seen.add(instance);
      try {
        if (isRecord(instance) && isFunction(instance.onDestroy)) {
          await instance.onDestroy();
        } else if (isRecord(instance) && isFunction(instance.ngOnDestroy)) {
          await instance.ngOnDestroy();
        }
      } catch (error) {
        errors.push(error);
      }
    }
    if (errors.length > 0) throw new AggregateError(errors, "Scope destruction failed");
  });
  scopeDestructions.set(scope, destruction);
  return destruction;
}`;

export interface GenerateOptions {
  rootDir: string;
  outDir: string;
  generateClient?: boolean;
  generatePermissions?: boolean;
  /** Prune unused root providers from compiled output (Angular Ivy AOT tree-shaking). */
  treeShakeUnusedProviders?: boolean;
  /** Incremental emitter state. Unchanged artifacts are not rewritten. */
  artifactHashes?: Map<string, string>;
}

export interface RenderedArtifacts {
  applicationCode: string;
  manifestJson: string;
  clientCode?: string;
  permissionsCode?: string;
}

/** Render application.ts and app.manifest.json content without file I/O. */
export function renderApplication(
  graph: ApplicationGraph,
  options: GenerateOptions,
): RenderedArtifacts {
  let modules = topoSortModules(graph.modules);
  if (options.treeShakeUnusedProviders) {
    const referencedTokens = new Set<string>();
    for (const mod of graph.modules) {
      for (const exp of mod.exports) referencedTokens.add(exp);
      for (const ctrl of mod.controllers) {
        for (const d of ctrl.deps) referencedTokens.add(d);
        for (const d of ctrl.optionalDeps ?? []) referencedTokens.add(d);
        for (const d of ctrl.selfDeps ?? []) referencedTokens.add(d);
        for (const d of ctrl.skipSelfDeps ?? []) referencedTokens.add(d);
        for (const d of ctrl.hostDeps ?? []) referencedTokens.add(d);
      }
      for (const p of mod.providers) {
        for (const d of p.deps ?? []) referencedTokens.add(d);
        for (const d of p.optionalDeps ?? []) referencedTokens.add(d);
        for (const d of p.selfDeps ?? []) referencedTokens.add(d);
        for (const d of p.skipSelfDeps ?? []) referencedTokens.add(d);
        for (const d of p.hostDeps ?? []) referencedTokens.add(d);
        if (p.useExisting) referencedTokens.add(p.useExisting);
      }
    }
    modules = modules.map((mod) => ({
      ...mod,
      providers: mod.providers.filter((p) => p.providedIn !== "root" || p.multi || referencedTokens.has(p.token) || p.exported),
    }));
  }
  const imports = new ImportManager();

  const factorySections: string[] = [];
  const descriptorEntries: string[] = [];
  for (const module of modules) {
    const gen = new ModuleGenerator(graph, module, imports);
    factorySections.push(...gen.renderFactories());
    descriptorEntries.push(gen.renderDescriptor());
  }

  const code = [
    HEADER,
    "",
    ...imports.render(options.rootDir, options.outDir),
    ...(imports.size > 0 ? [""] : []),
    INTERFACES,
    "",
    TYPE_GUARDS,
    "",
    "export function createCompiledModules(): CompiledModule[] {",
    "  return [",
    ...descriptorEntries.map((entry) => indent(entry, 4) + ","),
    "  ];",
    "}",
    "",
    "export async function initializeApplication(services: Record<string, unknown>): Promise<void> {",
    '  const initializers = [services.environmentInitializer ?? services["supacloud.environment-initializer"], services.appInitializer ?? services["supacloud.app-initializer"]];',
    "  for (const group of initializers) {",
    "    if (Array.isArray(group)) {",
    "      for (const init of group) {",
    '        if (isFunction(init)) await init();',
    "      }",
    '    } else if (isFunction(group)) {',
    "      await group();",
    "    }",
    "  }",
    "}",
    "",
    "export async function destroyApplication(services: Record<string, unknown>): Promise<void> {",
    '  const destroyRef = services.destroyRef ?? services["supacloud.destroy-ref"];',
    '  if (isRecord(destroyRef) && isFunction(destroyRef.destroy)) {',
    "    await destroyRef.destroy();",
    "  } else if (isRecord(destroyRef) && Array.isArray(destroyRef._teardowns)) {",
    "    for (const teardown of [...destroyRef._teardowns].reverse()) {",
    "      if (isFunction(teardown)) await teardown();",
    "    }",
    "  }",
    "  const instances = Object.values(services);",
    "  for (const inst of instances.reverse()) {",
    '    if (isRecord(inst) && isFunction(inst.onDestroy)) {',
    "      await inst.onDestroy();",
    '    } else if (isRecord(inst) && isFunction(inst.ngOnDestroy)) {',
    "      await inst.ngOnDestroy();",
    "    }",
    "  }",
    "}",
    "",
    ...factorySections,
    "",
  ].join("\n");

  const manifest: { version: number; modules: ModuleNode[]; externalTokens: string[] } = {
    version: 1,
    modules: graph.modules,
    externalTokens: graph.externalTokens,
  };

  const clientCode = options.generateClient ? renderClient(graph, options) : undefined;
  const permissionsCode = options.generatePermissions ? renderPermissions(graph) : undefined;

  return {
    applicationCode: code,
    manifestJson: JSON.stringify(manifest, null, 2) + "\n",
    clientCode,
    permissionsCode,
  };
}

/**
 * Generate static factory code (application.ts) and app.manifest.json.
 * Generated code imports only application classes and schemas, with no runtime reflection or container lookup.
 */
export async function generateApplication(
  graph: ApplicationGraph,
  options: GenerateOptions,
): Promise<string[]> {
  const rendered = renderApplication(graph, options);

  await mkdir(options.outDir, { recursive: true });
  const applicationPath = join(options.outDir, "application.ts");
  const manifestPath = join(options.outDir, "app.manifest.json");
  const written: string[] = [];
  if (await writeFileIfChanged(applicationPath, rendered.applicationCode, options.artifactHashes)) {
    written.push(applicationPath);
  }
  if (await writeFileIfChanged(manifestPath, rendered.manifestJson, options.artifactHashes)) {
    written.push(manifestPath);
  }
  if (rendered.clientCode) {
    const clientPath = join(options.outDir, "client.ts");
    if (await writeFileIfChanged(clientPath, rendered.clientCode, options.artifactHashes)) {
      written.push(clientPath);
    }
  }
  if (rendered.permissionsCode) {
    const permissionsPath = join(options.outDir, "permissions.ts");
    if (await writeFileIfChanged(permissionsPath, rendered.permissionsCode, options.artifactHashes)) {
      written.push(permissionsPath);
    }
  }
  return written;
}

async function writeFileIfChanged(
  path: string,
  content: string,
  hashes?: Map<string, string>,
): Promise<boolean> {
  const hash = createHash("sha1").update(content).digest("hex");
  if (hashes?.get(path) === hash) {
    try {
      await access(path);
      return false;
    } catch {
      // The cache is stale because the artifact was removed externally.
    }
  }
  await writeFileAtomic(path, content);
  hashes?.set(path, hash);
  return true;
}

async function writeFileAtomic(path: string, content: string): Promise<void> {
  const temporaryPath = `${path}.tmp-${process.pid}-${Math.random().toString(36).slice(2)}`;
  try {
    await writeFile(temporaryPath, content, "utf8");
    await rename(temporaryPath, path);
  } catch (error) {
    await unlink(temporaryPath).catch(() => undefined);
    throw error;
  }
}

type FactoryKind = "services" | "request" | "job";

function factoryOfScope(scope: Scope): FactoryKind {
  return scope === "application" ? "services" : scope;
}

/** Topologically sorts modules by imports (dependees first), preserving original relative ordering. */
function topoSortModules(modules: ModuleNode[]): ModuleNode[] {
  const byName = new Map(modules.map((m) => [m.name, m]));
  const visited = new Set<string>();
  const result: ModuleNode[] = [];
  const visit = (module: ModuleNode): void => {
    if (visited.has(module.name)) return;
    visited.add(module.name);
    for (const importName of module.imports) {
      const dep = byName.get(importName);
      if (dep && dep !== module) visit(dep);
    }
    result.push(module);
  };
  for (const module of modules) visit(module);
  return result;
}

function pascalName(name: string): string {
  const joined = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return joined || "App";
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

/** Manages generated file imports: automatically aliases symbols with the same name from different sources. */
class ImportManager {
  private readonly entries = new Map<string, { path: string; exported: string; package: boolean }>();

  get size(): number {
    return this.entries.size;
  }

  /** Registers a symbol and returns local identifier for generated code. importPath is relative to rootDir without extension. */
  add(exported: string, importPath?: string, importModule?: string): string {
    const path = importModule ?? importPath;
    const packageImport = importModule !== undefined;
    if (!path) return exported;
    for (const [local, entry] of this.entries) {
      if (entry.path === path && entry.exported === exported && entry.package === packageImport) return local;
    }
    let local = exported;
    let counter: number = 2;
    while (this.entries.has(local)) {
      local = `${exported}${counter}`;
      counter += 1;
    }
    this.entries.set(local, { path, exported, package: packageImport });
    return local;
  }

  render(rootDir: string, outDir: string): string[] {
    const byPath = new Map<string, { exported: string; local: string }[]>();
    for (const [local, entry] of this.entries) {
      const spec = entry.package
        ? entry.path
        : relativeImportPath(outDir, join(rootDir, `${entry.path}.ts`));
      const list = byPath.get(spec) ?? [];
      list.push({ exported: entry.exported, local });
      byPath.set(spec, list);
    }
    return [...byPath.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([spec, symbols]) => {
        const names = symbols
          .sort((a, b) => a.exported.localeCompare(b.exported))
          .map((s) => (s.local === s.exported ? s.exported : `${s.exported} as ${s.local}`))
          .join(", ");
        return `import { ${names} } from "${spec}";`;
      });
  }
}

/** Factory functions and CompiledModule descriptor generation for a single module. */
class ModuleGenerator {
  private readonly pascal: string;
  /** Token -> local variable name within each factory. */
  private readonly locals: Record<FactoryKind, Map<string, string>> = {
    services: new Map(),
    request: new Map(),
    job: new Map(),
  };

  constructor(
    private readonly graph: ApplicationGraph,
    private readonly module: ModuleNode,
    private readonly imports: ImportManager,
  ) {
    this.pascal = pascalName(module.name);
    if (
      module.providers.some((provider) => (provider.functionalInjects?.length ?? 0) > 0) ||
      module.controllers.some((controller) => (controller.functionalInjects?.length ?? 0) > 0)
    ) {
      imports.add("runInInjectionContext", undefined, "@supacloud/app");
    }
  }

  renderFactories(): string[] {
    const sections: string[] = [this.renderServicesFactory()];
    if (this.hasFactoryContent("request")) {
      sections.push(this.renderScopeFactory("request"));
      sections.push(this.renderScopeDestroyer("request"));
    }
    if (this.hasFactoryContent("job")) {
      sections.push(this.renderScopeFactory("job"));
      sections.push(this.renderScopeDestroyer("job"));
    }
    return sections;
  }

  renderDescriptor(): string {
    const lines: string[] = [
      `{`,
      `  name: ${JSON.stringify(this.module.name)},`,
      `  createServices: create${this.pascal}Services,`,
    ];
    if (this.hasFactoryContent("request")) {
      lines.push(`  createRequestScope: create${this.pascal}RequestScope,`);
      lines.push(`  destroyRequestScope: destroy${this.pascal}RequestScope,`);
    }
    if (this.hasFactoryContent("job")) {
      lines.push(`  createJobScope: create${this.pascal}JobScope,`);
      lines.push(`  destroyJobScope: destroy${this.pascal}JobScope,`);
    }
    lines.push(`  controllers: ${this.renderControllers()},`);
    lines.push(`  commands: ${this.renderCommands()},`);
    lines.push(`  jobs: ${this.renderJobs()},`);
    if (this.module.aspects && this.module.aspects.length > 0) {
      lines.push(`  aspects: ${this.renderAspects(this.module.aspects)},`);
    }
    lines.push(`}`);
    return lines.join("\n");
  }

  private hasFactoryContent(kind: Exclude<FactoryKind, "services">): boolean {
    return (
      this.module.providers.some((p) => factoryOfScope(p.scope) === kind) ||
      this.module.controllers.some((c) => factoryOfScope(c.scope) === kind)
    );
  }

  private renderControllers(): string {
    if (this.module.controllers.length === 0) return "[]";
    const items = this.module.controllers.map((controller) => {
      const routes = controller.routes.map((route) => {
        const fields: string[] = [
          `method: ${JSON.stringify(route.method)}`,
          `path: ${JSON.stringify(route.path)}`,
          `handler: ${JSON.stringify(route.handler)}`,
        ];
        for (const field of ["body", "params", "query", "response"] as const) {
          const symbol = route[field];
          if (symbol) {
            const local = this.imports.add(symbol, controller.schemaImports?.[symbol]);
            fields.push(`${field}: ${local}`);
          }
        }
        if (route.command) fields.push(`command: ${JSON.stringify(route.command)}`);
        if (route.guards && route.guards.length > 0) {
          fields.push(`guards: ${JSON.stringify(route.guards)}`);
        }
        if (route.canMatch && route.canMatch.length > 0) {
          fields.push(`canMatch: ${JSON.stringify(route.canMatch)}`);
        }
        if (route.canDeactivate && route.canDeactivate.length > 0) {
          fields.push(`canDeactivate: ${JSON.stringify(route.canDeactivate)}`);
        }
        if (route.resolvers && Object.keys(route.resolvers).length > 0) {
          fields.push(`resolvers: ${JSON.stringify(route.resolvers)}`);
        }
        if (route.redirectTo) {
          fields.push(`redirectTo: ${JSON.stringify(route.redirectTo)}`);
        }
        if (route.pathMatch) {
          fields.push(`pathMatch: ${JSON.stringify(route.pathMatch)}`);
        }
        if (route.paramTransforms && Object.keys(route.paramTransforms).length > 0) {
          fields.push(`paramTransforms: ${JSON.stringify(route.paramTransforms)}`);
        }
        if (route.paramDefaults && Object.keys(route.paramDefaults).length > 0) {
          fields.push(`paramDefaults: ${JSON.stringify(route.paramDefaults)}`);
        }
        if (route.queryTransforms && Object.keys(route.queryTransforms).length > 0) {
          fields.push(`queryTransforms: ${JSON.stringify(route.queryTransforms)}`);
        }
        if (route.queryDefaults && Object.keys(route.queryDefaults).length > 0) {
          fields.push(`queryDefaults: ${JSON.stringify(route.queryDefaults)}`);
        }
        if (route.title) {
          fields.push(`title: ${JSON.stringify(route.title)}`);
        }
        if (route.data && Object.keys(route.data).length > 0) {
          fields.push(`data: ${JSON.stringify(route.data)}`);
        }
        if (route.aspects && route.aspects.length > 0) {
          fields.push(`aspects: ${this.renderAspects(route.aspects)}`);
        }
        const invokerArgs = (route.handlerParams ?? []).map((hp) => {
          if (hp.kind === "param") {
            const accessor = `req.params?.[${JSON.stringify(hp.bindingName ?? hp.name)}]`;
            const fallback = hp.default !== undefined ? JSON.stringify(hp.default) : "undefined";
            if (hp.transform === "number") {
              return `(${accessor} !== undefined ? Number(${accessor}) : ${fallback})`;
            }
            if (hp.transform === "boolean") {
              return `(${accessor} !== undefined ? Boolean(${accessor}) : ${fallback})`;
            }
            if (hp.transform === "string") {
              return `(${accessor} !== undefined ? String(${accessor}) : ${fallback})`;
            }
            return `(${accessor} !== undefined ? ${accessor} : ${fallback})`;
          }
          if (hp.kind === "query") {
            const accessor = `req.query?.[${JSON.stringify(hp.bindingName ?? hp.name)}]`;
            const fallback = hp.default !== undefined ? JSON.stringify(hp.default) : "undefined";
            if (hp.transform === "number") {
              return `(${accessor} !== undefined ? Number(${accessor}) : ${fallback})`;
            }
            if (hp.transform === "boolean") {
              return `(${accessor} !== undefined ? Boolean(${accessor}) : ${fallback})`;
            }
            if (hp.transform === "string") {
              return `(${accessor} !== undefined ? String(${accessor}) : ${fallback})`;
            }
            return `(${accessor} !== undefined ? ${accessor} : ${fallback})`;
          }
          if (hp.kind === "body") return "req.body";
          if (hp.kind === "headers") return "req.headers";
          if (hp.kind === "context") return "(req.context ?? req)";
          return "undefined";
        });
        const callArgs = invokerArgs.length > 0 ? invokerArgs.join(", ") : "req";
        fields.push(
          `invoker: async (ctrl: unknown, req: { params?: Record<string, unknown>; query?: Record<string, unknown>; body?: unknown; headers?: Record<string, unknown>; context?: unknown }) => { ` +
          `if (!isRecord(ctrl)) throw new TypeError("Route controller is not an object"); ` +
          `const handler = ctrl[${JSON.stringify(route.handler)}]; ` +
          `if (typeof handler !== "function") throw new TypeError("Route handler ${route.handler} is not callable"); ` +
          `return await Reflect.apply(handler, ctrl, [${callArgs}]); }`,
        );
        return `{ ${fields.join(", ")} }`;
      });
      return [
        `{`,
        `  path: ${JSON.stringify(controller.path)},`,
        `  serviceKey: ${JSON.stringify(camelName(controller.className))},`,
        `  scope: ${JSON.stringify(controller.scope)},`,
        `  routes: [${routes.join(", ")}],`,
        `}`,
      ].join("\n");
    });
    return `[${items.map((item) => `\n${indent(item, 2)}`).join(",")}\n]`;
  }

  private renderCommands(): string {
    if (this.module.commands.length === 0) return "[]";
    return `[${this.module.commands.map((command) => {
      const fields = [
        `className: ${JSON.stringify(command.className)}`,
        `name: ${JSON.stringify(command.name)}`,
        `permission: ${JSON.stringify(command.permission ?? "")}`,
        `transaction: ${JSON.stringify(command.transaction)}`,
        ...(command.audit ? [`audit: ${JSON.stringify(command.audit)}`] : []),
        `idempotency: ${JSON.stringify(command.idempotency)}`,
        ...(command.standalone ? ["standalone: true"] : []),
        ...(command.aspects && command.aspects.length > 0
          ? [`aspects: ${this.renderAspects(command.aspects)}`]
          : []),
      ];
      return `{ ${fields.join(", ")} }`;
    }).join(", ")}]`;
  }

  private renderJobs(): string {
    const jobs = this.module.jobs ?? [];
    if (jobs.length === 0) return "[]";
    return `[${jobs.map((job) => `{ className: ${JSON.stringify(job.className)}, name: ${JSON.stringify(job.name)}, serviceKey: ${JSON.stringify(job.serviceKey)}, scope: ${JSON.stringify(job.scope)},${job.aspects && job.aspects.length > 0 ? ` aspects: ${this.renderAspects(job.aspects)},` : ""} }`).join(", ")}]`;
  }

  private renderAspects(aspects: Array<AspectRefNode>): string {
    return `[${aspects.map((aspect) => this.imports.add(aspect.name, aspect.importPath, aspect.importModule)).join(", ")}]`;
  }

  private renderServicesFactory(): string {
    return [
      `function create${this.pascal}Services(`,
      `  deps: Record<string, unknown>,`,
      `  imported: Record<string, Record<string, unknown>>,`,
      `): Record<string, unknown> {`,
      indent(this.renderFactoryBody("services"), 2),
      `}`,
    ].join("\n");
  }

  private renderScopeFactory(kind: "request" | "job"): string {
    const suffix = kind === "request" ? "RequestScope" : "JobScope";
    return [
      `async function create${this.pascal}${suffix}(`,
      `  services: Record<string, unknown>,`,
      `  ctx: unknown,`,
      `  imported: Record<string, Record<string, unknown>> = {},`,
      `): Promise<Record<string, unknown>> {`,
      `  const scope: Record<string, unknown> = {};`,
      `  try {`,
      indent(this.renderFactoryBody(kind, true), 4),
      `  } catch (error) {`,
      `    try {`,
      `      await destroy${this.pascal}${suffix}(scope);`,
      `    } catch (cleanupError) {`,
      `      console.error("supacloud: ${kind} scope rollback failed for ${this.module.name}", cleanupError);`,
      `    }`,
      `    throw error;`,
      `  }`,
      `}`,
    ].join("\n");
  }

  private renderScopeDestroyer(kind: "request" | "job"): string {
    const suffix = kind === "request" ? "RequestScope" : "JobScope";
    const plan: Array<{ key: string; index?: number }> = [];
    const multiIndices = new Map<string, number>();
    for (const provider of orderProviders(this.module.providers.filter((p) => factoryOfScope(p.scope) === kind))) {
      const index = provider.multi ? (multiIndices.get(provider.token) ?? 0) : undefined;
      if (index !== undefined) multiIndices.set(provider.token, index + 1);
      if (provider.kind !== "existing" && provider.hasOnDestroy) {
        plan.push({ key: camelName(provider.token), index });
      }
    }
    for (const controller of this.module.controllers) {
      if (factoryOfScope(controller.scope) === kind && controller.hasOnDestroy) {
        plan.push({ key: camelName(controller.className) });
      }
    }
    return [
      `async function destroy${this.pascal}${suffix}(scope: Record<string, unknown>): Promise<void> {`,
      `  await destroyScopeInstances(scope, ${JSON.stringify(plan)});`,
      `}`,
    ].join("\n");
  }

  /** Factory function body: instantiates providers and controllers for this scope in dependency topological order. */
  private renderFactoryBody(kind: FactoryKind, scoped = false): string {
    const providers = orderProviders(
      this.module.providers.filter((p) => factoryOfScope(p.scope) === kind),
    );
    const controllers = this.module.controllers.filter(
      (c) => factoryOfScope(c.scope) === kind,
    );

    const lines: string[] = [];
    const returns = new Map<string, string>();
    const multiGroups = new Map<string, string[]>();

    for (const provider of providers) {
      if (provider.multi) {
        const emitted = this.emitProvider(provider, kind, true);
        if (emitted.constLine) lines.push(emitted.constLine);
        if (scoped) {
          lines.push(
            `scope[${JSON.stringify(emitted.key)}] = [...(Array.isArray(scope[${JSON.stringify(emitted.key)}]) ? scope[${JSON.stringify(emitted.key)}] : []), ${emitted.expr}];`,
          );
        }
        const list = multiGroups.get(emitted.key) ?? [];
        list.push(emitted.expr);
        multiGroups.set(emitted.key, list);
      } else {
        const emitted = this.emitProvider(provider, kind, false);
        if (emitted.constLine) lines.push(emitted.constLine);
        if (scoped) {
          lines.push(`scope[${JSON.stringify(emitted.key)}] = ${emitted.expr};`);
        }
        returns.set(emitted.key, emitted.expr);
      }
    }
    for (const [key, exprs] of multiGroups) {
      returns.set(key, `[${exprs.join(", ")}]`);
    }
    for (const controller of controllers) {
      const emitted = this.emitController(controller, kind);
      lines.push(emitted.constLine);
      if (scoped) {
        lines.push(`scope[${JSON.stringify(emitted.key)}] = ${emitted.expr};`);
      }
      returns.set(emitted.key, emitted.expr);
    }
    if (scoped) {
      lines.push(`return scope;`);
      return lines.join("\n");
    }
    const entries = [...returns.entries()].map(([key, expr]) =>
      key === expr ? key : `${key}: ${expr}`,
    );
    lines.push(`return { ${entries.join(", ")} };`);
    return lines.join("\n");
  }

  private emitProvider(
    provider: ProviderNode,
    kind: FactoryKind,
    isMulti = false,
  ): { constLine?: string; key: string; expr: string } {
    const key = camelName(provider.token);
    switch (provider.kind) {
      case "class": {
        const useClass = this.imports.add(provider.useClass ?? provider.token, provider.importPath, provider.importModule);
        const args = provider.deps
          .map((dep) => this.depExpr(dep, kind, this.depOptions(provider, dep)))
          .join(", ");
        const local = this.localVar(isMulti ? (provider.useClass ?? `${provider.token}Item`) : provider.token, kind);
        return {
          constLine: `const ${local} = ${this.instantiate(useClass, args, kind, provider.functionalInjects)};`,
          key,
          expr: local,
        };
      }
      case "value": {
        const expr = provider.importPath || provider.importModule
          ? this.imports.add(provider.useValueExpr ?? "undefined", provider.importPath, provider.importModule)
          : (provider.useValueExpr ?? "undefined");
        const local = this.localVar(isMulti ? `${provider.token}Item` : provider.token, kind);
        return { constLine: `const ${local} = ${expr};`, key, expr: local };
      }
      case "factory": {
        if (provider.tokenKind === "injection-token" && !provider.useFactoryName) {
          const tokenIdent = this.imports.add(provider.token, provider.importPath, provider.importModule);
          const local = this.localVar(isMulti ? `${provider.token}Item` : provider.token, kind);
          const constLine = `const ${local} = resolveFactoryValue(${tokenIdent});`;
          return { constLine, key, expr: local };
        }
        const factory = this.imports.add(provider.useFactoryName ?? "", provider.importPath, provider.importModule);
        const args = provider.deps
          .map((dep) => this.depExpr(dep, kind, this.depOptions(provider, dep)))
          .join(", ");
        const local = this.localVar(isMulti ? (provider.useFactoryName ?? `${provider.token}Item`) : provider.token, kind);
        return { constLine: `const ${local} = ${factory}(${args});`, key, expr: local };
      }
      case "existing": {
        // Alias provider: does not create a new instance, directly references target expression.
        return {
          key,
          expr: this.depExpr(
            provider.useExisting ?? provider.token,
            kind,
            this.depOptions(provider, provider.useExisting ?? provider.token),
          ),
        };
      }
    }
  }

  private emitController(
    controller: ControllerNode,
    kind: FactoryKind,
  ): { constLine: string; key: string; expr: string } {
    const className = this.imports.add(controller.className, controller.importPath);
    const args = controller.deps
      .map((dep) => this.depExpr(dep, kind, this.depOptions(controller, dep)))
      .join(", ");
    const key = camelName(controller.className);
    const local = this.localVar(controller.className, kind);
    return {
      constLine: `const ${local} = ${this.instantiate(className, args, kind, controller.functionalInjects)};`,
      key,
      expr: local,
    };
  }

  /**
   * Functional inject() property initializers execute during `new`.
   * The compiler supplies a finite, generated token identity table for that
   * constructor call; it never performs provider discovery or token lookup.
   */
  private instantiate(
    className: string,
    args: string,
    kind: FactoryKind,
    functionalInjects?: FunctionalInjectNode[],
  ): string {
    if (!functionalInjects || functionalInjects.length === 0) {
      return `new ${className}(${args})`;
    }

    const clauses = functionalInjects.map((entry) => {
      const token = this.imports.add(entry.expression, entry.importPath, entry.importModule);
      const value = this.depExpr(entry.token, kind, {
        optional: entry.optional,
        self: entry.self,
        skipSelf: entry.skipSelf,
        host: entry.host,
      });
      return `if (token === ${token}) return ${value} as T;`;
    });
    const missing = `if (options?.optional) return undefined; throw new Error("Static inject token not available: " + String(token));`;
    const injector = [
      `{`,
      `get<T>(token: unknown, options?: { optional?: boolean; self?: boolean; skipSelf?: boolean; host?: boolean }): T | undefined {`,
      ...clauses,
      missing,
      `},`,
      `}`,
    ].join("\n");
    return `runInInjectionContext(${injector}, () => new ${className}(${args}))`;
  }

  /** Token -> local variable name in factory (camelCase, suffixed with digits on conflict). */
  private localVar(token: string, kind: FactoryKind): string {
    const locals = this.locals[kind];
    const existing = locals.get(token);
    if (existing) return existing;
    const base = camelName(token);
    let local = base;
    let counter: number = 2;
    while ([...locals.values()].includes(local)) {
      local = `${base}${counter}`;
      counter += 1;
    }
    locals.set(token, local);
    return local;
  }

  /**
   * Dependency resolution order:
   * Provider instantiated in current factory > Module application services (services.<key>) >
   * Services exported by imported modules (imported.<module>.<key>, accessed via services param in
   * request/job factories) > Platform deps (deps.<camelName>).
   */
  private depOptions(
    node: Pick<ProviderNode, "optionalDeps" | "selfDeps" | "skipSelfDeps" | "hostDeps"> | Pick<ControllerNode, "optionalDeps" | "selfDeps" | "skipSelfDeps">,
    token: string,
  ): { optional: boolean; self: boolean; skipSelf: boolean; host: boolean } {
    return {
      optional: node.optionalDeps?.includes(token) ?? false,
      self: node.selfDeps?.includes(token) ?? false,
      skipSelf: node.skipSelfDeps?.includes(token) ?? false,
      host: "hostDeps" in node ? (node.hostDeps?.includes(token) ?? false) : false,
    };
  }

  private depExpr(
    token: string,
    kind: FactoryKind,
    options: { optional?: boolean; self?: boolean; skipSelf?: boolean; host?: boolean } = {},
  ): string {
    const isOptional = options.optional ?? false;
    const isSelf = options.self ?? false;
    const isSkipSelf = options.skipSelf ?? false;
    if (kind === "request" && isRequestContextToken(token, this.graph.tokenNames)) return "ctx";
    if (kind === "job" && isJobContextToken(token, this.graph.tokenNames)) return "ctx";

    const own = this.module.providers.find((p) => p.token === token);
    const ownIsLocal = own && factoryOfScope(own.scope) === kind;
    if (own && ownIsLocal && !isSkipSelf) {
      if (factoryOfScope(own.scope) === kind && own.kind !== "existing") {
        return this.locals[kind].get(token) ?? camelName(token);
      }
      if (own.kind === "existing") {
        return this.depExpr(own.useExisting ?? token, kind, options);
      }
    }
    if (isSelf) {
      return isOptional ? "undefined" : `services.${camelName(token)}`;
    }

    // @Host() is intentionally a no-op for EnvironmentInjector-style scopes:
    // SupaCloud has no element-injector tree to impose a host boundary.
    for (const importName of this.module.imports) {
      const imported = this.graph.modules.find((m) => m.name === importName);
      if (!imported?.exports.includes(token)) continue;
      if (kind === "services") return `imported.${importName}.${camelName(token)}`;
      return `imported.${importName}.${camelName(token)}`;
    }

    for (const mod of this.graph.modules) {
      const rootProv = mod.providers.find((p) => p.token === token && p.providedIn === "root");
      if (rootProv) {
        return `imported.${mod.name}.${camelName(token)}`;
      }
    }

    if (isOptional && !this.graph.externalTokens.includes(token)) {
      return "undefined";
    }

    if (isSelf) return isOptional ? "undefined" : `services.${camelName(token)}`;
    if (kind === "services") return isOptional ? `(deps.${camelName(token)} ?? undefined)` : `deps.${camelName(token)}`;
    // request/job factories have no deps parameter; platform/external tokens are also passed via services.
    return isOptional ? `(services.${camelName(token)} ?? undefined)` : `services.${camelName(token)}`;
  }
}

/** Stable topological sort of providers within a factory: providers depending on peers in the same factory are placed after them. */
function orderProviders(providers: ProviderNode[]): ProviderNode[] {
  const remaining = [...providers];
  const emitted = new Set<string>();
  const result: ProviderNode[] = [];
  while (remaining.length > 0) {
    const index = remaining.findIndex((p) =>
      p.deps.every((dep) => {
        const depProvider = providers.find((x) => x.token === dep);
        return !depProvider || emitted.has(dep);
      }),
    );
    if (index === -1) {
      // Circular dependency: output in original order (validateGraph already reported circular-dependency).
      result.push(...remaining.splice(0));
      break;
    }
    const [provider] = remaining.splice(index, 1);
  emitted.add(provider.token);
  result.push(provider);
}
return result;
}

/**
 * Generates typed API client in client.ts from discovered Controllers and Routes.
 * Modeled after Angular HttpClient and typed contract clients.
 */
export function renderClient(graph: ApplicationGraph, _options?: GenerateOptions): string {
  const controllerEntries: string[] = [];
  const allRoutes: Array<{
    method: string;
    path: string;
    controller: string;
    handler: string;
    command?: string;
    guards?: string[];
    canMatch?: string[];
    canDeactivate?: string[];
    resolvers?: Record<string, string>;
    redirectTo?: string;
    pathMatch?: "full" | "prefix";
    paramTransforms?: Record<string, "number" | "boolean" | "string">;
    paramDefaults?: Record<string, unknown>;
    queryTransforms?: Record<string, "number" | "boolean" | "string">;
    queryDefaults?: Record<string, unknown>;
    title?: string;
    data?: Record<string, unknown>;
  }> = [];

  for (const module of graph.modules) {
    for (const controller of module.controllers) {
      const controllerKey = camelName(controller.className.replace(/Controller$/, ""));
      const routeMethods: string[] = [];

      for (const route of controller.routes) {
        const fullPath = joinRoutePaths(controller.path, route.path);
        allRoutes.push({
          method: route.method,
          path: fullPath,
          controller: controller.className,
          handler: route.handler,
          command: route.command,
          guards: route.guards,
          canMatch: route.canMatch,
          canDeactivate: route.canDeactivate,
          resolvers: route.resolvers,
          redirectTo: route.redirectTo,
          pathMatch: route.pathMatch,
          paramTransforms: route.paramTransforms,
          paramDefaults: route.paramDefaults,
          queryTransforms: route.queryTransforms,
          queryDefaults: route.queryDefaults,
          title: route.title,
          data: route.data,
        });

        routeMethods.push(`
    ${route.handler}: (options: {
      params${(route.pathParams && route.pathParams.length > 0) || (fullPath.match(/:([a-zA-Z0-9_]+)/g) ?? []).length > 0 ? "" : "?"}: ${(route.pathParams && route.pathParams.length > 0) || (fullPath.match(/:([a-zA-Z0-9_]+)/g) ?? []).length > 0 ? `{ ${((route.pathParams && route.pathParams.length > 0 ? route.pathParams : (fullPath.match(/:([a-zA-Z0-9_]+)/g) ?? []).map((p) => p.slice(1)))).map((p) => `${p}: string | number`).join("; ")} }` : "Record<string, string | number>"};
      query?: Record<string, unknown>;
      body?: unknown;
      headers?: Record<string, string>;
    }${(route.pathParams && route.pathParams.length > 0) || (fullPath.match(/:([a-zA-Z0-9_]+)/g) ?? []).length > 0 ? "" : " = {}"}) => request(${JSON.stringify(route.method)}, ${JSON.stringify(fullPath)}, options),`);
      }

      controllerEntries.push(`
  ${controllerKey}: {${routeMethods.join("")}
  },`);
    }
  }

  return [
    HEADER,
    "",
    "export interface ClientRequestOptions {",
    "  params?: Record<string, string | number>;",
    "  query?: Record<string, unknown>;",
    "  body?: unknown;",
    "  headers?: Record<string, string>;",
    "}",
    "",
    "export type ResponseDecoder<T> = (value: unknown) => T;",
    "",
    "export type HttpInterceptorFn = (",
    "  req: { method: string; url: string; headers: Record<string, string>; body?: unknown },",
    "  next: (req: { method: string; url: string; headers: Record<string, string>; body?: unknown }) => Promise<Response>,",
    ") => Promise<Response>;",
    "",
    "export interface ApiClientConfig {",
    "  baseUrl?: string;",
    "  fetch?: typeof fetch;",
    "  headers?: Record<string, string> | (() => Record<string, string> | Promise<Record<string, string>>);",
    "  interceptors?: HttpInterceptorFn[];",
    "}",
    "",
    "export const API_ROUTES = " + JSON.stringify(allRoutes, null, 2) + " as const;",
    "",
    "export type AppRoutePath = typeof API_ROUTES[number]['path'];",
    "",
    "/**",
    " * Type-safe URL builder replacing route path parameters and appending query parameters.",
    " */",
    "export function buildRouteUrl(",
    "  path: string,",
    "  params?: Record<string, string | number>,",
    "  query?: Record<string, unknown>,",
    "): string {",
    "  let url = path;",
    "  if (params) {",
    "    for (const [key, value] of Object.entries(params)) {",
    "      url = url.replace(`:${key}`, encodeURIComponent(String(value)));",
    "    }",
    "  }",
    "  if (query) {",
    "    const searchParams = new URLSearchParams();",
    "    for (const [k, v] of Object.entries(query)) {",
    "      if (v !== undefined && v !== null) searchParams.set(k, String(v));",
    "    }",
    "    const qs = searchParams.toString();",
    '    if (qs) url += (url.includes("?") ? "&" : "?") + qs;',
    "  }",
    "  return url;",
    "}",
    "",
    "export function createApiClient(config: ApiClientConfig = {}) {",
    "  const fetcher = config.fetch ?? globalThis.fetch.bind(globalThis);",
    '  const baseUrl = (config.baseUrl ?? "").replace(/\\/+$/, "");',
    "",
    "  async function request<T>(",
    "    method: string,",
    "    path: string,",
    "    options: ClientRequestOptions,",
    "    decode: ResponseDecoder<T>,",
    "  ): Promise<T>;",
    "  async function request(",
    "    method: string,",
    "    path: string,",
    "    options?: ClientRequestOptions,",
    "  ): Promise<unknown>;",
    "  async function request<T>(",
    "    method: string,",
    "    path: string,",
    "    options: ClientRequestOptions = {},",
    "    decode?: ResponseDecoder<T>,",
    "  ): Promise<T | unknown> {",
    "    let url = `${baseUrl}${path}`;",
    "    if (options.params) {",
    "      for (const [key, value] of Object.entries(options.params)) {",
    "        url = url.replace(`:${key}`, encodeURIComponent(String(value)));",
    "      }",
    "    }",
    "    if (options.query) {",
    "      const searchParams = new URLSearchParams();",
    "      for (const [k, v] of Object.entries(options.query)) {",
    "        if (v !== undefined && v !== null) searchParams.set(k, String(v));",
    "      }",
    "      const qs = searchParams.toString();",
    '      if (qs) url += (url.includes("?") ? "&" : "?") + qs;',
    "    }",
    '    const customHeaders = typeof config.headers === "function" ? await config.headers() : config.headers;',
    "    const headers: Record<string, string> = {",
    '      "content-type": "application/json",',
    "      ...customHeaders,",
    "      ...options.headers,",
    "    };",
    "    const interceptors = config.interceptors ?? [];",
    "    const executeChain = (",
    "      index: number,",
    "      reqPayload: { method: string; url: string; headers: Record<string, string>; body?: unknown },",
    "    ): Promise<Response> => {",
    "      if (index < interceptors.length) {",
    "        return interceptors[index](reqPayload, (nextPayload) => executeChain(index + 1, nextPayload));",
    "      }",
    "      return fetcher(reqPayload.url, {",
    "        method: reqPayload.method,",
    "        headers: reqPayload.headers,",
    "        body: reqPayload.body !== undefined ? JSON.stringify(reqPayload.body) : undefined,",
    "      });",
    "    };",
    "    const response = await executeChain(0, { method, url, headers, body: options.body });",
    "    if (!response.ok) {",
    "      const errBody = await response.text();",
    "      throw new Error(`API request failed: ${method} ${path} -> ${response.status} ${errBody}`);",
    "    }",
    '    const contentType = response.headers?.get("content-type") ?? "";',
    "    let value: unknown;",
    '    if (contentType.includes("application/json")) {',
    "      value = await response.json();",
    "    } else {",
    "      value = await response.text();",
    "    }",
    "    return decode ? decode(value) : value;",
    "  }",
    "",
    "  return {",
    "    request,",
    "    buildRouteUrl,",
    "    routes: API_ROUTES,",
    ...controllerEntries,
    "  };",
    "}",
    "",
    "export type ApiClient = ReturnType<typeof createApiClient>;",
    "",
  ].join("\n");
}

/**
 * Generates static permissions and route permission bindings in permissions.ts.
 */
export function renderPermissions(graph: ApplicationGraph): string {
  const permissions = new Set<string>();
  const bindings: Array<{
    method: string;
    path: string;
    controller: string;
    handler: string;
    command?: string;
    permission?: string;
  }> = [];

  for (const module of graph.modules) {
    for (const command of module.commands) {
      if (command.permission) permissions.add(command.permission);
    }
    for (const controller of module.controllers) {
      for (const route of controller.routes) {
        let perm: string | undefined;
        if (route.command) {
          const cmd = module.commands.find((c) => c.className === route.command);
          perm = cmd?.permission;
        }
        if (perm) permissions.add(perm);
        bindings.push({
          method: route.method,
          path: joinRoutePaths(controller.path, route.path),
          controller: controller.className,
          handler: route.handler,
          command: route.command,
          permission: perm,
        });
      }
    }
  }

  const sortedPerms = [...permissions].sort();
  const enumEntries = sortedPerms.map((perm) => {
    const key = pascalName(perm.replace(/[^A-Za-z0-9]+/g, " "));
    return `  ${key}: ${JSON.stringify(perm)},`;
  });

  return [
    HEADER,
    "",
    "export const AppPermissions = {",
    ...enumEntries,
    "} as const;",
    "",
    "export type AppPermission = (typeof AppPermissions)[keyof typeof AppPermissions];",
    "",
    "export interface RoutePermissionBinding {",
    "  method: string;",
    "  path: string;",
    "  controller: string;",
    "  handler: string;",
    "  command?: string;",
    "  permission?: string;",
    "}",
    "",
    "export const RoutePermissions: RoutePermissionBinding[] = " + JSON.stringify(bindings, null, 2) + ";",
    "",
    "export function hasPermission(granted: string[], required: AppPermission | string): boolean {",
    '  return granted.includes("*") || granted.includes(required);',
    "}",
    "",
  ].join("\n");
}
